insert into sport (uuid, sport, price, category, active)
values (RANDOM_UUID(), 'AlpineSki', 0.00, 'Winter', false),
       (RANDOM_UUID(), 'BackcountrySki', 0.00, 'Winter', false),
       (RANDOM_UUID(), 'Badminton', 0.00, 'Ball', false),
       (RANDOM_UUID(), 'Canoeing', 0.00, 'Wasser', false),
       (RANDOM_UUID(), 'Crossfit', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'EBikeRide', 0.00, 'Rad', false),
       (RANDOM_UUID(),'Elliptical', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'EMountainBikeRide', 0.00, 'Rad', false),
       (RANDOM_UUID(), 'Golf', 0.00, 'Ball', false),
       (RANDOM_UUID(),'GravelRide', 0.00, 'Rad', false),
       (RANDOM_UUID(),'Handcycle', 0.00, 'Rad', false),
       (RANDOM_UUID(),'HighIntensityIntervalTraining', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'Hike', 0.00, 'Wandern', false),
       (RANDOM_UUID(),'IceSkate', 0.00, 'Winter', false),
       (RANDOM_UUID(),'InlineSkate', 0.00, 'Fun', false),
       (RANDOM_UUID(),'Kayaking', 0.00, 'Wasser', false),
       (RANDOM_UUID(),'Kitesurf', 0.00, 'Wasser', false),
       (RANDOM_UUID(),'MountainBikeRide', 0.00, 'Rad', false),
       (RANDOM_UUID(),'NordicSki', 0.00, 'Winter', false),
       (RANDOM_UUID(),'Pickleball', 0.00, 'Ball', false),
       (RANDOM_UUID(),'Pilates', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'Racquetball', 0.00, 'Ball', false),
       (RANDOM_UUID(),'Ride', 0.00, 'Rad', false),
       (RANDOM_UUID(),'RockClimbing', 0.00, 'Klettern', false),
       (RANDOM_UUID(),'RollerSki', 0.00, 'Winter', false),
       (RANDOM_UUID(),'Rowing', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'Run', 0.00, 'Laufen', false),
       (RANDOM_UUID(),'Sail', 0.00, 'Wasser', false),
       (RANDOM_UUID(),'Skateboard', 0.00, 'Fun', false),
       (RANDOM_UUID(),'Snowboard', 0.00, 'Winter', false),
       (RANDOM_UUID(),'Snowshoe', 0.00, 'Winter', false),
       (RANDOM_UUID(),'Soccer', 0.00, 'Ball', false),
       (RANDOM_UUID(),'Squash', 0.00, 'Ball', false),
       (RANDOM_UUID(),'StairStepper', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'StandUpPaddling', 0.00, 'Wasser', false),
       (RANDOM_UUID(),'Surfing', 0.00, 'Wasser', false),
       (RANDOM_UUID(),'Swim', 0.00, 'Wasser', false),
       (RANDOM_UUID(),'TableTennis', 0.00, 'Ball', false),
       (RANDOM_UUID(),'Tennis', 0.00, 'Ball', false),
       (RANDOM_UUID(),'TrailRun', 0.00, 'Laufen', false),
       (RANDOM_UUID(),'Velomobile', 0.00, 'Rad', false),
       (RANDOM_UUID(),'VirtualRide', 0.00, 'Rad', false),
       (RANDOM_UUID(),'VirtualRow', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'VirtualRun', 0.00, 'Laufen', false),
       (RANDOM_UUID(),'Walk', 0.00, 'Wandern', false),
       (RANDOM_UUID(),'WeightTraining', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'Wheelchair', 0.00, 'Wandern', false),
       (RANDOM_UUID(),'Windsurf', 0.00, 'Wasser', false),
       (RANDOM_UUID(),'Workout', 0.00, 'Fitness', false),
       (RANDOM_UUID(),'Yoga', 0.00, 'Fitness', false);
