name: CD to CapRover

on:
  workflow_run:
    workflows: ["Java CI with Gradle"]
    types:
      - completed

jobs:
  deploy:
    if:   github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/jederkilometer .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/jederkilometer

      - name: Deploy to CapRover
        run: |
          npm install -g caprover
          caprover deploy --caproverUrl "${{ secrets.CAPROVER_SERVER }}" \
                          --appName "${{ secrets.CAPROVER_APP_NAME }}" \
                          --caproverPassword "${{ secrets.CAPROVER_PASSWORD }}" \
                          --imageName "${{ secrets.DOCKERHUB_USERNAME }}/jederkilometer"